### ISSUE TITLE
feature request: websocket support for subscribe method events

### ISSUE THREAD

**Issue by Luca-Blight** [whats-good/nexus#65]
"Eth_subscribe" method is used to establish connection for real-time event notification.
However Nexus does not have websocket support which is a precursor component.

Subscribe event to consider:

[alchemy_minedTransactions](https://docs.alchemy.com/reference/alchemy-minedtransactions)
[alchemy_pendingTransactions](https://docs.alchemy.com/reference/alchemy-pendingtransactions)
[newPendingTransactions](https://docs.alchemy.com/reference/newpendingtransactions)
[newHeads](https://docs.alchemy.com/reference/newheads)
[logs](https://docs.alchemy.com/reference/logs)

More info in this link:
(https://docs.alchemy.com/reference/eth-subscribe)

**Comment by mechanical-turk** [comment]
experimental support to websockets added in: https://github.com/whats-good/nexus/pull/88

will work on stabilizing this in the next few releases
